[tool.poetry]
authors = ["Robert Bamler <robert.bamler@uni-tuebingen.de>"]
classifiers = [
  "Topic :: System :: Archiving :: Compression",
  "Intended Audience :: Science/Research",
]
description = "Composable entropy coding primitives for research and production (Python and Rust)."
documentation = "https://bamler-lab.github.io/constriction/apidoc/python/"
homepage = "https://bamler-lab.github.io/constriction/"
keywords = ["compression", "machine-learning", "entropy-coding", "range-coding", "ANS"]
license = "MIT OR Apache-2.0 OR BSL-1.0"
name = "constriction"
readme = "README.md"
repository = "https://github.com/bamler-lab/constriction/"
version = "0.1.2"

[tool.poetry.dependencies]
numpy = "^1.20"
python = "^3.7,<3.10"

[tool.poetry.dev-dependencies]
autopep8 = "*"
flake8 = "^3.5"
maturin = "==0.9.4"
pdoc3 = "^0.9.2"
pylint = "^2.6"
pytest = "^6.1"
pytest-runner = "*"
scipy = "^1.6.3"
wheel = "*"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry_core>=1.0.0"]
